name:                agg
version:             0.1.0
github:              "holmisen/agg"
license:             BSD3
author:              "Johan Holmquist"
maintainer:          "holmisen@gmail.com"
copyright:           "2018 Johan Holmquist"

# extra-source-files:
# - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            ???

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Program for basic data transformations.

dependencies:
- base >= 4.7 && < 5

# library:
#   source-dirs: src

executables:
  agg:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - containers
    - parsec
    - text
    - transformers
