resolver: lts-10.5

# A package marked 'extra-dep: true' will only be built if demanded by a
# non-dependency (i.e. a user package), and its test suites and benchmarks
# will not be run. This is useful for tweaking upstream packages.
packages:
- .

# Control whether we use the GHC we find on the path
# system-ghc: true

# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
